# Multiple Linear Regression Machine Learning Project for Student Marks Prediction

# Problem Statement

Predict marks using hours,age,internet

# Import libraries

In [94]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset

In [95]:
df=pd.read_csv('multiple_linear_regression.csv')

In [96]:
df

     hours  age  internet  marks
0     6.83   15         1  78.50
1     6.56   16         0  76.74
2      NaN   17         1  78.68
3     5.67   18         0  71.82
4     8.67   19         1  84.19
..     ...  ...       ...    ...
196   8.56   19         1  84.68
197   8.94   20         1  86.75
198   6.60   15         1  78.05
199   8.35   16         1  83.50
200   4.15   15         0  81.45

[201 rows x 4 columns]

# dataset Understaning

In [97]:
df.head()

   hours  age  internet  marks
0   6.83   15         1  78.50
1   6.56   16         0  76.74
2    NaN   17         1  78.68
3   5.67   18         0  71.82
4   8.67   19         1  84.19

In [98]:
df.shape

(201, 4)

In [99]:
df.describe()

            hours         age    internet       marks
count  196.000000  201.000000  201.000000  201.000000
mean     6.981429   17.467662    0.552239   77.951244
std      1.266266    1.720523    0.498505    4.919626
min      4.150000   15.000000    0.000000   68.570000
25%      5.757500   16.000000    0.000000   73.400000
50%      7.110000   17.000000    1.000000   77.770000
75%      8.082500   19.000000    1.000000   82.300000
max      8.990000   20.000000    1.000000   86.990000

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   hours     196 non-null    float64
 1   age       201 non-null    int64
 2   internet  201 non-null    int64
 3   marks     201 non-null    float64
dtypes: float64(2), int64(2)
memory usage: 6.4 KB

# Data cleaning

In [101]:
df.head()

   hours  age  internet  marks
0   6.83   15         1  78.50
1   6.56   16         0  76.74
2    NaN   17         1  78.68
3   5.67   18         0  71.82
4   8.67   19         1  84.19

In [102]:
df.columns[df.isna().any()]
df.hours=df.hours.fillna(df.hours.mean())

In [103]:
df.columns[df.isnull().any()]

Index([], dtype='object')

# Feature selection

In [104]:
x=df.iloc[:, :-1]
x

        hours  age  internet
0    6.830000   15         1
1    6.560000   16         0
2    6.981429   17         1
3    5.670000   18         0
4    8.670000   19         1
..        ...  ...       ...
196  8.560000   19         1
197  8.940000   20         1
198  6.600000   15         1
199  8.350000   16         1
200  4.150000   15         0

[201 rows x 3 columns]

In [105]:
y=df.iloc[:,-1].values
y

array([78.5 , 76.74, 78.68, 71.82, 84.19, 81.18, 76.99, 85.46, 70.66,
       77.82, 75.37, 83.88, 79.5 , 80.76, 83.08, 76.03, 76.04, 85.11,
       82.5 , 80.58, 82.18, 83.36, 70.67, 75.02, 70.96, 83.33, 74.75,
       75.65, 74.15, 80.17, 82.27, 76.14, 71.1 , 84.35, 83.08, 76.76,
       81.24, 78.21, 73.08, 83.23, 70.27, 86.41, 71.1 , 82.84, 82.38,
       72.96, 77.46, 70.11, 72.38, 71.41, 72.22, 77.77, 84.44, 71.45,
       82.21, 85.48, 75.03, 86.65, 70.9 , 71.7 , 73.61, 79.41, 76.19,
       80.43, 85.78, 70.06, 81.25, 81.7 , 69.27, 82.79, 71.8 , 71.79,
       74.97, 78.61, 77.59, 72.33, 72.08, 77.33, 70.05, 73.34, 84.  ,
       82.93, 76.63, 75.36, 77.29, 72.87, 73.4 , 81.74, 71.85, 84.6 ,
       79.56, 82.1 , 72.08, 79.1 , 81.01, 76.48, 75.39, 68.57, 83.64,
       82.3 , 75.18, 82.03, 82.99, 79.26, 77.55, 77.07, 72.1 , 73.25,
       74.25, 70.58, 81.08, 75.04, 76.38, 80.86, 78.42, 74.44, 70.34,
       85.04, 73.61, 75.55, 76.2 , 82.69, 76.83, 79.53, 83.57, 85.95,
       76.02, 77.65, 77.01, 74.49, 73.19, 71.86, 75.8 , 72.46, 78.39,
       83.48, 83.15, 71.22, 85.98, 83.91, 84.58, 80.31, 82.55, 75.52,
       83.82, 85.15, 82.75, 74.34, 82.02, 86.12, 71.87, 76.7 , 81.7 ,
       70.78, 78.45, 70.2 , 83.37, 75.52, 81.57, 80.72, 80.81, 79.49,
       79.17, 77.07, 82.04, 71.94, 81.6 , 70.79, 82.68, 83.08, 71.18,
       77.63, 77.78, 70.4 , 73.02, 71.11, 85.96, 73.64, 84.24, 78.17,
       77.19, 71.83, 86.99, 83.87, 71.5 , 79.63, 85.1 , 72.01, 77.27,
       79.87, 73.14, 70.51, 84.03, 79.64, 74.24, 81.67, 84.68, 86.75,
       78.05, 83.5 , 81.45])

# Train-Test split

In [106]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

# Train model

In [107]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x,y)

LinearRegression()

# Prediction

In [108]:
y_pred=model.predict(x_test)

In [109]:
y_pred

array([77.09234239, 74.90400385, 82.15730174, 70.62924931, 81.93868638,
       73.48188072, 70.86866152, 76.29498013, 82.85860955, 72.26869845,
       77.41797605, 74.56344144, 73.30866547, 85.16889514, 83.40682347,
       81.29374253, 83.81425832, 78.00449426, 84.07637058, 81.01479831,
       71.20145263, 83.83695837, 82.30972015, 70.72530376, 82.35450639,
       78.87772798, 81.63240173, 76.29626947, 80.60088151, 79.15605833,
       81.51890147, 83.31015516, 85.129977  , 73.08098946, 83.11485371,
       76.16845432, 83.05452486, 75.60989041, 80.10454965, 76.21195123,
       83.03769291])

# Model Evalution

In [110]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
import numpy as np

print('MAE:',mean_absolute_error(y_test,y_pred))
print('MSE:',mean_squared_error(y_test,y_pred))
print('RMSE:',np.sqrt(mean_squared_error(y_test,y_pred)))
print('R2:',r2_score(y_test,y_pred))

MAE: 0.8959059762381768
MSE: 1.1943204529654519
RMSE: 1.092849693674959
R2: 0.9419206748468386

# Make your own Predition

In [111]:
a=[[5.2,20,1]]
PredictedmodelResult=model.predict(a)

C:\Users\veera\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [112]:
print(PredictedmodelResult)

[71.17098127]

# Mannual Calculation

In [113]:
m=model.coef_
print(m)

[ 3.76288007 -0.02270005 -0.0434969 ]

In [114]:
b=model.intercept_
print(b)

52.1015028398388